# Jesus Bolivar
## Week 11 11/2/2023
### Python numpy Universal functions

In [1]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [3]:
arr= np.random.randn(10)#return a sample(or samples) from the 'standard normal' distribution

In [4]:
arr

array([-0.54262157,  0.01607629,  1.03319755, -1.69924253, -0.8012416 ,
        0.42944634,  0.86528398, -1.07681669, -1.97676109, -0.15119953])

In [5]:
arr.mean()

-0.39038788488086484

In [6]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)

In [7]:
arr1

array([-2.57218223, -0.23663128,  0.16708183,  0.45505661, -0.94904639,
       -0.01301145,  0.87893042,  0.14830884,  1.6600385 , -1.36726863])

In [8]:
arr2

array([-1.16485993,  1.40741168,  0.08509887,  0.30541953,  0.63108669,
       -0.04360574,  0.60902389, -0.45666252,  0.44005571,  0.09306875])

In [9]:
np.add(arr1,arr2) #Add arguments element-wise.

array([-3.73704216,  1.17078039,  0.25218071,  0.76047613, -0.3179597 ,
       -0.0566172 ,  1.4879543 , -0.30835368,  2.10009421, -1.27419988])

In [10]:
#maximum
np.maximum(arr1,arr2)

array([-1.16485993,  1.40741168,  0.16708183,  0.45505661,  0.63108669,
       -0.01301145,  0.87893042,  0.14830884,  1.6600385 ,  0.09306875])

In [11]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [12]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
# Array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [17]:
# using where
# replace values of an array, using where
np.where(arr<4, 0, -1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [18]:
np.where((arr < 4) & (arr > 2), 0, -1)

array([[-1, -1, -1],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_bool = [True, False, True, False, True]
arr1

array([1, 2, 3, 4, 5])

In [20]:
arr2

array([10, 20, 30, 40, 50])

In [21]:
arr_bool

[True, False, True, False, True]

In [22]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, False), (5, 50, True)]

In [23]:
# using list comprehension 
#arr = np.array([r1 if c else r2 for ra,r2,c in zip(arr1,arr2,arr_bool)])
#arr

In [24]:
#arr = np.where(arr_bool, arr1,arr2)
#arr

In [1]:
import numpy as np
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [2]:
arr1

array([[1, 2],
       [3, 4]])

In [3]:
arr2

array([[5, 6],
       [7, 8]])

In [4]:
sample_arr = [True,False]
arr_bool = np.random.choice(sample_arr, 10)
arr_bool

array([ True, False,  True, False,  True,  True, False, False, False,
        True])

In [5]:
arr1

array([[1, 2],
       [3, 4]])

In [6]:
arr2

array([[5, 6],
       [7, 8]])

In [9]:
arr_bool = np.random.choice(sample_arr, size=4).reshape(2,2)
arr_bool

array([[ True,  True],
       [ True,  True]])

In [10]:
np.where(arr_bool, arr1,arr2)

array([[1, 2],
       [3, 4]])

In [11]:
arr = np.random.randn(3,3)
arr

array([[ 0.8525124 ,  1.33543121,  1.28289473],
       [ 1.16419767, -1.25939068,  0.2307239 ],
       [ 1.30993531, -0.29709485, -0.43246593]])

In [12]:
np.where(arr<0, 0,arr)

array([[0.8525124 , 1.33543121, 1.28289473],
       [1.16419767, 0.        , 0.2307239 ],
       [1.30993531, 0.        , 0.        ]])

In [13]:
# any 
arr_bool = np.random.choice(sample_arr, size=10)
arr_bool

array([False, False, False,  True, False, False,  True, False, False,
       False])

In [14]:
arr_bool.any() #Returns True if any elements eveluate to True.

True

In [15]:
arr_bool.all()#Returns True if all elements of 'a' eveluate to True.

False

In [16]:
#unique() Finds the unique elements of an array.
fruits = np.array([['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana']])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [17]:
# in1d Test whether each element of a 1-D array is also present in a second 
np.in1d(['Apple', 'Cherry', 'Grape'],fruits)

array([ True,  True, False])

In [18]:
fruits

array([['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana']],
      dtype='<U6')

In [19]:
'Apple' in fruits

True

In [20]:
#Descriptive Statistical Measures
arr_2d = np.arange(1,10).reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d.ndim

2

In [26]:
arr_2d.sum()

45

In [27]:
#axis0
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr_2d.sum(0)

array([12, 15, 18])

In [29]:
arr_2d.sum(1)

array([ 6, 15, 24])

In [30]:
np.sum(arr_2d, axis=0)

array([12, 15, 18])

In [31]:
np.sum(arr_2d, axis=1)

array([ 6, 15, 24])

In [32]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr_2d.mean()

5.0

In [34]:
arr_2d.mean(0)


array([4., 5., 6.])

In [35]:
arr_2d.mean(1)


array([2., 5., 8.])

In [36]:
np.mean(arr_2d,axis=0)

array([4., 5., 6.])

In [37]:
np.mean(arr_2d,axis=1)

array([2., 5., 8.])

In [38]:
arr_2d.var()

6.666666666666667

In [39]:
arr_2d.var(0)

array([6., 6., 6.])

In [40]:
arr_2d.var(1)

array([0.66666667, 0.66666667, 0.66666667])

In [41]:
np.var(arr_2d,axis=0)

array([6., 6., 6.])

In [42]:
np.var(arr_2d,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [43]:
arr = np.random.randn(3,3)
arr

array([[ 0.55044336,  0.04176396, -0.40967123],
       [ 1.53358475,  0.87025488,  0.91604698],
       [-1.43821467, -1.39001309,  0.39180606]])

In [44]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 0.19380201, -1.04184962, -0.52772855],
       [ 0.33326184, -0.75248431,  0.224266  ],
       [ 0.87704626, -1.17606083, -0.62619526]])

In [48]:
arr = np.random.random((4,4))
arr

array([[0.81950787, 0.44580894, 0.13018309, 0.13303261],
       [0.34934315, 0.61838122, 0.99645992, 0.10809167],
       [0.35752271, 0.02493419, 0.50055751, 0.37250133],
       [0.32404644, 0.01364499, 0.16566382, 0.48023591]])

In [50]:
from numpy.random import random
arr = random((4,4))
arr

array([[0.47055369, 0.54894159, 0.83258873, 0.25164109],
       [0.248687  , 0.48609603, 0.78415464, 0.81786684],
       [0.3868983 , 0.38092535, 0.5178899 , 0.19563751],
       [0.05766162, 0.45746754, 0.61129676, 0.97730834]])

In [51]:
num = np.random.randint(10,50)
num

22

In [57]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

In [58]:
arr1


array([1, 2, 3])

In [59]:
arr2

array([4, 5, 6])

In [60]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [62]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [63]:
arr1

array([[1, 2],
       [3, 4]])

In [64]:
arr2

array([[5, 6],
       [7, 8]])

In [65]:
arr = np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
arr.shape

(4, 2)

In [67]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [69]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [70]:
narr = np.split(arr,2)
narr

[array([1, 2, 3]), array([4, 5, 6])]

In [71]:
narr = np.split(arr,3)
narr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [73]:
narr[0]

array([1, 2])

In [74]:
narr[1]

array([3, 4])

In [75]:
narr[2]

array([5, 6])

In [76]:
narr = np.array_split(arr,4)
narr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [77]:
narr[0]

array([1, 2])

In [78]:
narr[-1]

array([6])