# Jesus Bolivar
## Week 10 10/26/2023
### Python numpy - processing arrays

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]
arr = np.array(my_list)
arr

array([11, 22, 33, 44, 55, 66, 77])

In [3]:
# Creating an array from a nested list
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list = [lst1,lst2]
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [5]:
arr = np.array(my_list)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [6]:
arr.ndim

2

In [7]:
arr.dtype

dtype('int32')

In [8]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']

arr_str = np.array(fruits)
arr_str

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [9]:
arr_str.ndim

1

In [10]:
arr_str.dtype

dtype('<U6')

In [12]:
d = ['Orange', 'Apple', 'Cherry', 'Grape',1,2,3,4,5, [6,7,8,9,10], True, False]

arr_obj = np.array(d)
arr_obj

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10]), True, False], dtype=object)

In [13]:
arr_obj.dtype

dtype('O')

In [14]:
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [15]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst, dtype='S')
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [16]:
arr.dtype

dtype('S1')

In [17]:
arr = np.array(lst, dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr = np.array(lst, dtype='i8')
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [20]:
arr.dtype

dtype('int64')

In [21]:
# Converting data type on existing arrays
arr = np.array(['1', '2', '4', '5'], dtype='i')
arr


array([1, 2, 4, 5], dtype=int32)

In [22]:
scores = [78.5, 89.9, 90.3, 89.9, 89.67]
arr = np.array(scores)
arr

array([78.5 , 89.9 , 90.3 , 89.9 , 89.67])

In [26]:
arr_int = arr.astype('i')
arr_int

array([78, 89, 90, 89, 89], dtype=int32)

In [24]:
print(arr)

[78.5  89.9  90.3  89.9  89.67]


In [27]:
arr.dtype

dtype('float64')

In [28]:
lst = [1,0,1,1,0,0,1,0,1,0,1,0]
arr = np.array(lst)
arr

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [29]:
arr.dtype

dtype('int32')

In [30]:
arr_bool = arr.astype(bool)
arr_bool

array([ True, False,  True,  True, False, False,  True, False,  True,
       False,  True, False])

In [31]:
arr

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [32]:
# NumPy array copy vs view, vs = with the list
lst = [1,2,3,4,5]
lst_e = lst

In [33]:
lst

[1, 2, 3, 4, 5]

In [34]:
lst_e

[1, 2, 3, 4, 5]

In [35]:
lst[0]=55

In [36]:
lst

[55, 2, 3, 4, 5]

In [37]:
lst_e

[55, 2, 3, 4, 5]

In [38]:
arr= np.array(lst)
arr

array([55,  2,  3,  4,  5])

In [39]:
arr_c = arr.copy()
arr_c

array([55,  2,  3,  4,  5])

In [40]:
# the copy is a new array
arr

array([55,  2,  3,  4,  5])

In [41]:
arr_c

array([55,  2,  3,  4,  5])

In [44]:
arr[0]=11
print(arr)
print(arr_c)

[11  2  3  4  5]
[55  2  3  4  5]


In [45]:
arr_c[-1]=0
print(arr)
print(arr_c)

[11  2  3  4  5]
[55  2  3  4  0]


In [46]:
list = [11,12,13,14,15]
arr = np.array(lst)
arr_v = arr.view() # view is just a view of the original array

In [47]:
print(arr)
print(arr_v)

[55  2  3  4  5]
[55  2  3  4  5]


In [48]:
arr[-1]=55
print(arr)
print(arr_v)

[55  2  3  4 55]
[55  2  3  4 55]


In [49]:
arr[0]=88
print(arr)
print(arr_v)

[88  2  3  4 55]
[88  2  3  4 55]


In [50]:
print(arr_v.base)
print(arr_c.base)


[88  2  3  4 55]
None


In [51]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]
arr = np.array(my_list)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [52]:
arr.ndim

2

In [53]:
arr.shape

(2, 5)

In [54]:
arr = np.array(lst1)
arr

array([1, 2, 3, 4, 5])

In [55]:
arr.ndim

1

In [59]:
arr = np.array(lst1, ndmin=4)
arr

array([[[[1, 2, 3, 4, 5]]]])

In [60]:
arr.ndim

4

In [61]:
arr.shape

(1, 1, 1, 5)

In [62]:
arr = np.array(lst1, ndmin=6)
arr

array([[[[[[1, 2, 3, 4, 5]]]]]])

In [63]:
arr.ndim

6

In [64]:
arr.shape

(1, 1, 1, 1, 1, 5)

In [65]:
arr.shape[0]

1

In [70]:
arr = np.array([     [2,3,4,5],     [6,7,8,9]    ])
arr.shape

(2, 4)

In [71]:
arr.shape[0]

2

In [72]:
arr

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [73]:
arr.shape[1]

4

In [74]:
# Reading data from files
f = open("data.txt","w")
f.write("1,2,3\n")
f.write("4,5,6\n")
f.close()

#read
f = open("data.txt", "r")
print(f.read())

1,2,3
4,5,6



In [77]:
arr = np.genfromtxt("data.txt",dtype=None, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr.dtype

dtype('int32')

In [ ]:
arr = np.loadtxt("data1.txt"), dtype