# Jesus Bolivar
## Week 11 11/2/2023
### Python numpy Universal functions

In [1]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [3]:
arr= np.random.randn(10)#return a sample(or samples) from the 'standard normal' distribution

In [4]:
arr

array([-0.54262157,  0.01607629,  1.03319755, -1.69924253, -0.8012416 ,
        0.42944634,  0.86528398, -1.07681669, -1.97676109, -0.15119953])

In [5]:
arr.mean()

-0.39038788488086484

In [6]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)

In [7]:
arr1

array([-2.57218223, -0.23663128,  0.16708183,  0.45505661, -0.94904639,
       -0.01301145,  0.87893042,  0.14830884,  1.6600385 , -1.36726863])

In [8]:
arr2

array([-1.16485993,  1.40741168,  0.08509887,  0.30541953,  0.63108669,
       -0.04360574,  0.60902389, -0.45666252,  0.44005571,  0.09306875])

In [9]:
np.add(arr1,arr2) #Add arguments element-wise.

array([-3.73704216,  1.17078039,  0.25218071,  0.76047613, -0.3179597 ,
       -0.0566172 ,  1.4879543 , -0.30835368,  2.10009421, -1.27419988])

In [10]:
#maximum
np.maximum(arr1,arr2)

array([-1.16485993,  1.40741168,  0.16708183,  0.45505661,  0.63108669,
       -0.01301145,  0.87893042,  0.14830884,  1.6600385 ,  0.09306875])

In [11]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [12]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
# Array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [17]:
# using where
# replace values of an array, using where
np.where(arr<4, 0, -1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [18]:
np.where((arr < 4) & (arr > 2), 0, -1)

array([[-1, -1, -1],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_bool = [True, False, True, False, True]
arr1

array([1, 2, 3, 4, 5])

In [20]:
arr2

array([10, 20, 30, 40, 50])

In [21]:
arr_bool

[True, False, True, False, True]

In [22]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, False), (5, 50, True)]

In [23]:
# using list comprehension 
#arr = np.array([r1 if c else r2 for ra,r2,c in zip(arr1,arr2,arr_bool)])
#arr

In [24]:
#arr = np.where(arr_bool, arr1,arr2)
#arr

In [25]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [26]:
arr1

array([[1, 2],
       [3, 4]])

In [27]:
arr2

array([[5, 6],
       [7, 8]])

In [28]:
sample_arr = [True,False]
arr_bool = np.random.choice(sample_arr, 5)
arr_bool

array([ True,  True,  True,  True,  True])

In [29]:
arr1

array([[1, 2],
       [3, 4]])

In [30]:
arr2

array([[5, 6],
       [7, 8]])

In [31]:
#arr_bool = np.array([np.random.choice(sample_arr, size=2).reshape(2,2)
#arr_bool