# Jesus Bolivar
## Week 11 10/31/2023 - 11/2/2023
### Python numpy creating, processing, transporting arrays

In [1]:
import numpy as np
arr_2d = np.array([ [1,2,3,4], [5,6,7,8]  ])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

In [2]:
#zeros() returns a new array of given shape and type, filled with zeros.
arr = np.zeros(10)
arr

In [3]:
arr.dtype

In [4]:
arr_2d = np.zeros((5,5))
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
arr_2d.ndim

2

In [6]:
arr_2d.dtype

dtype('float64')

In [7]:
#ones() returns a new array of given shape and type, filled with ones.
arr_2d = np.ones((5,5))
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
(5, 5)
float64


In [8]:
arr_2d = np.empty((2,2,4)) # it creates a new NumPy array with random values.
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[[4.67296746e-307 1.69121096e-306 8.90104239e-307 1.33511969e-306]
  [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]]

 [[6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
  [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]]
3
(2, 2, 4)
float64


In [9]:
arr_2d = np.empty((3,3), dtype=int)
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[980444020 842084143 774909495]
 [976301616 842019381        48]
 [        0         0         0]]
2
(3, 3)
int32


In [10]:
# arange: return evenly spaced valyes with a given interval
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [12]:
# reshape an array
arr_1d = np.arange(1,13,1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
arr_2d 

array([[980444020, 842084143, 774909495],
       [976301616, 842019381,        48],
       [        0,         0,         0]])

In [14]:
arr_2d = arr_1d.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
len(arr_1d)

12

In [16]:
len(arr_2d)

2

In [17]:
arr_2d.shape

(2, 6)

In [18]:
arr_3d = np.arange(1,13).reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [19]:
arr_3d = np.arange(1,13).reshape(2,2,3)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
#arr_3d = np.arange(1,13).reshape(2,3,3)
#arr_3d

In [21]:
arr_2d.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr_1d[0] = 100

In [23]:
arr_1d

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [24]:
arr_2d

array([[100,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12]])

In [25]:
#pass -1 as the value and NumPy will calculate this number for you 
arr_3d = np.arange(1,9).reshape(2,2,-1)

In [26]:
arr_3d.shape

(2, 2, 2)

In [27]:
arr = np.arange(1,9).reshape(2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
for n in arr_1d:
    print(n)

100
2
3
4
5
6
7
8
9
10
11
12


In [30]:
arr_2d

array([[100,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12]])

In [31]:
for n in arr_2d:
    print(n)

[100   2   3   4   5   6]
[ 7  8  9 10 11 12]


In [32]:
for n in arr_2d:
    for num in n:
        print(num)

100
2
3
4
5
6
7
8
9
10
11
12


In [33]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
#nditer iterates on each scalar element in the np array
for num in np.nditer(arr_2d):
    print(num)

100
2
3
4
5
6
7
8
9
10
11
12


In [35]:
arr_2d = np.arange(1,13).reshape(4,3)
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
arr_2d[:,::2]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [37]:
for num in np.nditer(arr_2d[:,::2]):
    print(num)

1
3
4
6
7
9
10
12


In [38]:
arr_1d = np.arange(1,13)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
for idx, num in np.ndenumerate(arr_1d):
    print(idx, num)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [40]:
for idx, num in np.ndenumerate(arr_2d):
    print(idx, num)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
(3, 0) 10
(3, 1) 11
(3, 2) 12


In [41]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
for idx, num in np.ndenumerate(arr_3d):
    print(idx, num)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [44]:
arr_3d.shape

(2, 2, 2)

In [45]:
# operations *, +, -, *, etc
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr_1d * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [47]:
arr_2d * arr_2d

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [48]:
arr_2d + arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [49]:
arr_2d**2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]], dtype=int32)

In [50]:
arr_2d**3

array([[   1,    8,   27],
       [  64,  125,  216],
       [ 343,  512,  729],
       [1000, 1331, 1728]], dtype=int32)

In [51]:
1 / arr_2d

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333]])

In [52]:
arr_2d = np.zeros((9,9))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
arr_2d.shape

(9, 9)

In [54]:
arr_2d.shape[0]

9

In [55]:
arr_2d.shape[1]

9

In [56]:
arr_2d[0]= 10

In [57]:
arr_2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [58]:
for idx in range(arr_2d.shape[0]):
    arr_2d[idx] = 10 # change each row element to 10
    
arr_2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [59]:
for idx in range(arr_2d.shape[0]):
    arr_2d[idx] = idx * 2 # multiply the idx by 2, idx = 0,1,2,3,4,5,6,7,8
    
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [60]:
arr_2d[1:7]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [61]:
arr_2d[::2]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [62]:
arr_2d[::2, :4]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.],
       [12., 12., 12., 12.],
       [16., 16., 16., 16.]])

In [63]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [64]:
# extract specific rows
arr_2d[[3,6]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [65]:
arr_2d[[1,3,6]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [66]:
#extract specific colums
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [67]:
arr_2d[:,[3,7]]

array([[ 0.,  0.],
       [ 2.,  2.],
       [ 4.,  4.],
       [ 6.,  6.],
       [ 8.,  8.],
       [10., 10.],
       [12., 12.],
       [14., 14.],
       [16., 16.]])

In [68]:
arr_2d[:,[3,5,7]]

array([[ 0.,  0.,  0.],
       [ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.],
       [12., 12., 12.],
       [14., 14., 14.],
       [16., 16., 16.]])

In [69]:
arr = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0)) ])
arr

array([['Sarah', (8.0, 7.0)],
       ['John', (6.0, 7.0)]], dtype=object)

In [70]:
print(arr)
print(arr.ndim)
print(arr.shape)

[['Sarah' (8.0, 7.0)]
 ['John' (6.0, 7.0)]]
2
(2, 2)


In [71]:
arr[:,0]

array(['Sarah', 'John'], dtype=object)

In [72]:
arr[:,-1]

array([(8.0, 7.0), (6.0, 7.0)], dtype=object)

In [73]:
arr[0,0]

'Sarah'

In [74]:
arr[0]

array(['Sarah', (8.0, 7.0)], dtype=object)

In [75]:
arr[1,1]

(6.0, 7.0)

In [76]:
arr[1]

array(['John', (6.0, 7.0)], dtype=object)

In [77]:
# .T Same as self.transpose(),
arr = np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [78]:
arr.shape

(9, 5)

In [79]:
arr.ndim

2

In [80]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [81]:
arr.T.shape

(5, 9)

In [82]:
arr_t = arr.T

In [83]:
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [84]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [85]:
arr[0]=100
arr

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44]])

In [86]:
arr_t

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [87]:
np.transpose(arr)

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [88]:
np.transpose(arr).shape

(5, 9)

In [89]:
arr.transpose()

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [90]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
arr.shape

(2, 4)

In [92]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [93]:
arr.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [94]:
arr.shape[0]

2

In [95]:
arr.shape[1]

4

In [96]:
arr.transpose((0,1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [97]:
arr.transpose((1,0)) #swap axis 0 with axis 1

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [98]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [99]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [100]:
arr_3d.T.shape

(2, 5, 2)

In [101]:
arr_3d.transpose()

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [102]:
arr_3d.transpose().shape

(2, 5, 2)

In [103]:
arr_3d.transpose((0,1,2)) # no change in the axis, same order

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [104]:
arr_3d.transpose((1,0,2)) # change axis 0 with axis 1

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [105]:
arr_3d.transpose((1,0,2)).shape

(5, 2, 2)

In [106]:
arr_3d.transpose((1,2,0))

array([[[ 0, 10],
        [ 1, 11]],

       [[ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17]],

       [[ 8, 18],
        [ 9, 19]]])

In [107]:
arr_3d.transpose((1,2,0)).shape

(5, 2, 2)

In [108]:
arr_3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [109]:
arr_3d.transpose((0,2,1)).shape

(2, 2, 5)

In [110]:
# swap axes
arr = np.array([[1,2,3,4]])
arr

array([[1, 2, 3, 4]])

In [111]:
arr.ndim

2

In [112]:
arr.shape

(1, 4)

In [113]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3],
       [4]])

In [114]:
arr.swapaxes(0,1).shape

(4, 1)

In [115]:
arr_3d = np.arange(45).reshape(3,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [116]:
arr_3d.ndim

3

In [117]:
arr_3d.shape

(3, 5, 3)

In [118]:
arr_3d.swapaxes(1,2)

array([[[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]],

       [[15, 18, 21, 24, 27],
        [16, 19, 22, 25, 28],
        [17, 20, 23, 26, 29]],

       [[30, 33, 36, 39, 42],
        [31, 34, 37, 40, 43],
        [32, 35, 38, 41, 44]]])

In [119]:
arr_3d.swapaxes(1,2).shape

(3, 3, 5)

In [120]:
arr_3d.swapaxes(0,2)

array([[[ 0, 15, 30],
        [ 3, 18, 33],
        [ 6, 21, 36],
        [ 9, 24, 39],
        [12, 27, 42]],

       [[ 1, 16, 31],
        [ 4, 19, 34],
        [ 7, 22, 37],
        [10, 25, 40],
        [13, 28, 43]],

       [[ 2, 17, 32],
        [ 5, 20, 35],
        [ 8, 23, 38],
        [11, 26, 41],
        [14, 29, 44]]])

In [121]:
arr_3d.swapaxes(1,2)

array([[[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]],

       [[15, 18, 21, 24, 27],
        [16, 19, 22, 25, 28],
        [17, 20, 23, 26, 29]],

       [[30, 33, 36, 39, 42],
        [31, 34, 37, 40, 43],
        [32, 35, 38, 41, 44]]])

In [122]:
arr_3d[0] = 100

In [123]:
arr_3d

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29]],

       [[ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]]])

In [124]:
arr_3d.swapaxes(1,2)

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 15,  18,  21,  24,  27],
        [ 16,  19,  22,  25,  28],
        [ 17,  20,  23,  26,  29]],

       [[ 30,  33,  36,  39,  42],
        [ 31,  34,  37,  40,  43],
        [ 32,  35,  38,  41,  44]]])